language: php
php:
  - 5.4
  - 5.3
   
before_script:
  - composer install
  - pear install phpunit/DbUnit
  - mysql -e 'create database IF NOT EXISTS quick_tag;'
  
script: phpunit --configuration travis.xml
